### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Sonjyoti Kafka Test",
  "email": "sonjyotimca@bhu.ac.in",
  "address": "Boko",
  "dateOfBirth": "2001-01-09",
  "registeredDate": "2026-01-15"
}

###